name: Build Only

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew :patches:buildAndroid clean

      - name: Find build artifact
        id: find-artifact
        run: |
          echo "artifact_path=$(find patches/build -type f -name '*.rvp' | head -n 1)" >> $GITHUB_OUTPUT
      
      - name: Show found artifact
        run: echo "Arquivo encontrado em ${{ steps.find-artifact.outputs.artifact_path }}"
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: patches-build
          path: ${{ steps.find-artifact.outputs.artifact_path }}

